from __future__ import annotations

import os
import re
from dataclasses import dataclass

from openai import OpenAI

from edraft.config import IdentityConfig, LLMConfig
from edraft.models import MailboxMessage, ThreadContext
from edraft.text_utils import to_prompt_text, truncate_text


class DraftGenerationError(RuntimeError):
    """Raised when the LLM draft generation step fails."""


@dataclass(slots=True)
class DraftPrompt:
    system: str
    user: str


class DraftGenerator:
    def __init__(
        self,
        config: LLMConfig,
        identity: IdentityConfig,
        *,
        client: OpenAI | None = None,
    ) -> None:
        if config.provider != "openai":
            raise DraftGenerationError(
                f"Unsupported LLM provider '{config.provider}'. This MVP supports only OpenAI."
            )
        self.config = config
        self.identity = identity
        api_key = os.getenv("OPENAI_API_KEY")
        if client is None and not api_key:
            raise DraftGenerationError("OPENAI_API_KEY must be set to generate drafts.")
        self.client = client or OpenAI(api_key=api_key)

    def generate(self, message: MailboxMessage, thread_context: ThreadContext) -> str:
        prompt = self.build_prompt(message, thread_context)
        try:
            request_kwargs = {
                "model": self.config.model,
                "input": [
                    {"role": "system", "content": prompt.system},
                    {"role": "user", "content": prompt.user},
                ],
                "store": False,
            }
            if self.config.reasoning_effort:
                request_kwargs["reasoning"] = {"effort": self.config.reasoning_effort}
            response = self.client.responses.create(
                **request_kwargs,
            )
        except Exception as exc:
            raise DraftGenerationError(f"LLM request failed: {exc}") from exc
        output = (getattr(response, "output_text", "") or "").strip()
        if not output:
            raise DraftGenerationError("LLM response did not contain text output")
        return self._finalize_body(output)

    def build_prompt(self, message: MailboxMessage, thread_context: ThreadContext) -> DraftPrompt:
        incoming_text = truncate_text(
            to_prompt_text(message.body_content, message.body_content_type) or message.body_preview,
            self.config.max_input_chars // 2,
        )
        history_sections = []
        remaining_budget = max(self.config.max_input_chars - len(incoming_text), 1000)
        per_message_budget = max(500, remaining_budget // max(len(thread_context.related_messages), 1))
        for item in thread_context.related_messages:
            history_text = truncate_text(
                to_prompt_text(item.body_content, item.body_content_type) or item.body_preview,
                per_message_budget,
            )
            history_sections.append(
                "\n".join(
                    [
                        f"From: {item.sender_name or item.sender_address}",
                        f"Subject: {item.subject}",
                        f"Received: {item.received_at.isoformat() if item.received_at else 'unknown'}",
                        f"Body:\n{history_text}",
                    ]
                )
            )
        history_block = "\n\n---\n\n".join(history_sections) if history_sections else "(no earlier thread context found)"

        system = "\n".join(
            [
                "You draft email replies for a human reviewer.",
                "The reply must be concise, professional, and natural.",
                "Never invent facts, promises, dates, or commitments.",
                "If context is insufficient, ask a clarifying question instead of guessing.",
                "Prefer shorter replies unless the thread clearly needs more detail.",
                "Return only the email body text.",
                "Do not include a subject line, 'Re:', recipient headers, or any metadata.",
                "Use readable plain-text formatting with blank lines between paragraphs.",
                "If you include bullets or numbered items, put each item on its own line.",
                "Do not mention that you are an AI or that the reply is autogenerated.",
                f"Reply as {self.identity.name} <{self.identity.email}>.",
                self.config.style_instructions.strip(),
            ]
        )
        user = "\n".join(
            [
                "Draft a reply to the current email. The draft should be ready for manual review.",
                "",
                f"Current email subject: {message.subject}",
                f"From: {message.sender_name or message.sender_address} <{message.sender_address}>",
                f"To: {', '.join(recipient.address for recipient in message.to_recipients) or '(none)'}",
                f"Cc: {', '.join(recipient.address for recipient in message.cc_recipients) or '(none)'}",
                "",
                "Current email body:",
                incoming_text,
                "",
                "Recent thread context:",
                history_block,
            ]
        )
        return DraftPrompt(system=system, user=user)

    def _finalize_body(self, body: str) -> str:
        text = body.replace("\r\n", "\n").replace("\r", "\n").strip()
        text = self._strip_leading_headers(text)
        text = self._normalize_list_formatting(text)
        text = re.sub(r"\n{3,}", "\n\n", text).strip()
        return self._with_signature(text)

    def _strip_leading_headers(self, body: str) -> str:
        lines = body.splitlines()
        while lines:
            line = lines[0].strip()
            if not line:
                lines.pop(0)
                continue
            if re.match(r"^(subject|from|to|cc|bcc)\s*:", line, flags=re.IGNORECASE):
                lines.pop(0)
                continue
            break
        return "\n".join(lines).strip()

    def _normalize_list_formatting(self, body: str) -> str:
        text = body
        text = re.sub(r"(?<!\n)\s+(?=(?:[-*]|\d+\.)\s)", "\n", text)
        text = re.sub(r":\s+(?=(?:[-*]|\d+\.)\s)", ":\n", text)
        return text

    def _with_signature(self, body: str) -> str:
        if not self.config.signature_block:
            return body
        signature = self.config.signature_block.strip()
        cleaned_body = self._strip_trailing_signoff(body.rstrip(), signature)
        if not cleaned_body:
            return signature
        return f"{cleaned_body}\n\n{signature}"

    def _strip_trailing_signoff(self, body: str, signature: str) -> str:
        lines = body.splitlines()
        signature_lines = [line.strip() for line in signature.splitlines() if line.strip()]

        while lines:
            while lines and not lines[-1].strip():
                lines.pop()
            if not lines:
                break
            if self._tail_matches_signature(lines, signature_lines):
                del lines[-len(signature_lines) :]
                continue
            if len(lines) >= 2 and self._is_self_signoff_block(lines[-2:]):
                del lines[-2:]
                continue
            if self._is_self_name_line(lines[-1]):
                lines.pop()
                continue
            break

        while lines and not lines[-1].strip():
            lines.pop()
        return "\n".join(lines).strip()

    def _tail_matches_signature(self, lines: list[str], signature_lines: list[str]) -> bool:
        if not signature_lines or len(lines) < len(signature_lines):
            return False
        tail = [line.strip().casefold() for line in lines[-len(signature_lines) :]]
        return tail == [line.casefold() for line in signature_lines]

    def _is_self_signoff_block(self, lines: list[str]) -> bool:
        if len(lines) != 2:
            return False
        closing = lines[0].strip().casefold()
        return closing in {
            "thanks",
            "thanks,",
            "thank you",
            "thank you,",
            "best",
            "best,",
            "regards",
            "regards,",
            "sincerely",
            "sincerely,",
        } and self._is_self_name_line(lines[1])

    def _is_self_name_line(self, line: str) -> bool:
        normalized = re.sub(r"[^a-z0-9]+", " ", line.casefold()).strip()
        if not normalized:
            return False

        name_variants = {
            re.sub(r"[^a-z0-9]+", " ", self.identity.name.casefold()).strip(),
            re.sub(r"[^a-z0-9]+", " ", self.identity.email.split("@", 1)[0].casefold()).strip(),
        }
        name_variants.update(part for part in name_variants.copy() for part in part.split() if part)
        return normalized in {variant for variant in name_variants if variant}
